### ISSUE TITLE
x13binary integration

### ISSUE THREAD

**Issue by christophsax** [christophsax/seasonal#124]
@eddelbuettel: x13binary is still loaded because of `Depends:`. Is there a reason why not to use `Imports:x13binary`? I tried it and is seems to work.

**Comment by eddelbuettel** [comment]
Yup. It got late on my end.  I may have added the (outdated) `Depends:` because of some initial trouble which may have gotten away with `system.file()` use.  If it works now, stick to `Imports`. Or maybe it was because my thinking was as follows:

- In a way, we are doing "neither".  
- We are not adding R functions to the search path (hence no cost of `Depends:`)
- We are not using R functions (hence no `Imports:`)

It doesn't really matter, but _generally speaking_ `Imports:` is better so please switch as you see fit.  Your package :)

**Comment by christophsax** [comment]
I added the Depends:, because this is what we recommend in x13binary. Will
thus change it to Imports: in both places.

**Comment by eddelbuettel** [comment]
:+1:  

I also used `Imports: seasonal` in the nascent gunsales packages, but it is more obvious there as it uses `seas()` and `final()`.
