### ISSUE TITLE
problem with file link getCall

### ISSUE THREAD

**Issue by mcooganj** [christophsax/seasonal#228]
I just installed 1.7.0 (source) from CRAN and got the following warning. 

`file link 'getCall' in package 'stats' does not exist and so has been treated as a topic`

Things seem to be working fine just now -- but i thought it odd that there was an issue with stats. there's nothing custom about my stats package. 

I tried the github version, and got the same warning.

**Comment by christophsax** [comment]
This was tested on multiple platforms, and I newer saw such a thing. 

Can you run in a fresh R session and copy/paste the output:

```r
ls()
R.version
packageVersion("stats")
packageVersion("seasonal")
getCall
```

**Comment by mcooganj** [comment]
sure: 

> ls()
character(0)
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray               
> packageVersion('stats')
[1] ‘3.5.1’
> packageVersion('seasonal')
[1] ‘1.7.0’
> getCall
function (x, ...) 
UseMethod("getCall")
<bytecode: 0x0000000016418bc8>
<environment: namespace:stats>

**Comment by christophsax** [comment]
Seems harmless.

I think this is because the documentation links to `stats::getCall`, which is documented together with `stats::uptdate` (also see [here](https://github.com/klutometis/roxygen/issues/707)). 

Could be probably fixed by changing or removing the documentation link to `stats::getCall`, which does not have much meaning anyway. Not clear to me why I haven't seen that before and only on your computer. I don't see it if I install from source on Linux or macOS.

I guess you wont see the warnings as soon as the binaries are on CRAN (very soon).

**Comment by mcooganj** [comment]
Agreed. Seems harmless.
