### ISSUE TITLE
Compression warning on Winbuilder: JSS vignette

### ISSUE THREAD

**Issue by christophsax** [christophsax/seasonal#328]
On Winbuilder, I get the following WARNING:

```
* checking sizes of PDF files under 'inst/doc' ... WARNING
  'gs+qpdf' made some significant size reductions:
     compacted 'seas.pdf' from 596Kb to 269Kb
```

I cannot reproduce it and don't understand what Winbuilder is doing.

I tried the following:

- R CMD build --compact-vignettes=gs+qpdf on Mac, Windows, and Linux. The resulting file is approximately 600Kb everywhere, same as the input.

- `tools::compactPDF("seas.pdf", gs_quality = "ebook", verbose = TRUE)`

       ==> (new=2.11485e+06)/(old=610372) = 3.46485 .. not worth using
- `tools::compactPDF("seas.pdf", gs_quality = "none", verbose = TRUE)`

      ==> (new=609273)/(old=610372) = 0.998199 .. not worth using
- Separately calling qpdf and gs (only on Mac) leads to no further reduction:
  `qpdf seas.pdf seas_compressed.pdf`  -> 609Kb
  `gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -sOutputFile=seas_compressed.pdf seas.pdf`  -> 2.2Mb

**Comment by eddelbuettel** [comment]
What I switched too in a few packages is too .... preprocess the whole pdf vignette locally, include the generated (and compressed !!) pdf in the package and then use the trick by Mark van der Loo to have a minimal Rnw which ... just includes the pdf.    That seems to avoid it because we then only operate on a (pre-)compressed pdf.   I would have to check if I do that with other JSS papers too. 

I think the key between what you do and what winbuilder does is that winbuilder may not default to the ` --compact-vignettes=gs+qpdf` argument so that it has something to compress left?   I have not had an issue on submission.

**Comment by christophsax** [comment]
Thanks!

You are suggesting I should ignore it and just submit and, if lucky, we don't have the issue there?

I talked to Uwe at the UseR and he has offered some help. If unlucky, he still may support me.

Preprocessing would be plan B, I guess.

**Comment by eddelbuettel** [comment]
Yes.  Especially if you recently spoke with him -- just sit the issue out, and I review.  That cannot possibly be a real blocker.  I would have to count them but I probably have a number of packages with pdf vignettes and I only do the pre-processing in some (mostly to avoid stumbling over esoteric fonts or styles; JSS should be fine at CRAN of course) so "wait and see" seems fine.

**Comment by eddelbuettel** [comment]
You could also just ask the above on r-package-devel, he may even chime.  Describe how on win-builder you get the warning, how _building with the compression option_ locally does not and may ask/wonder if winbuilder does not compress by default or if there is another trick.

**Comment by christophsax** [comment]
Will submit once CRAN is back from vacation.

**Comment by christophsax** [comment]
Sorry, it took me a long time. In the end, it was all on my side, and I had to update to the latest ghostscript. On the mac, that was:

```
brew update
brew upgrade ghostscript
```

Now on CRAN 🎉
